TasmoAdmin/TasmoAdmin

README.md
The URL of the Home Assistant add-on has been changed, to match the recent renaming of the project.
=> :books: Updates Home Assistant add-on URL

tasmoadmin/includes/top.php
This is especially useful when running the application with a reverse proxy which
maps the URL to something different which can not be autodetected.
=> chore: Allow to set the base url via an env variable TASMO_BASEURL

tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/devices.php, tasmoadmin/resources/js/device_filter.js
An input field for an instant filter is displayed on top of the device list. Devices without a match in the name will be hidden while typing the filter...
For instance, by typing "Light", only devices matching "Light" in their name will be shown in the list.  The filter is case-insensitive.
The placement of the input field may need change.
=> Adds a filter for the device list view

.docker/rootfs/etc/php7/php-fpm.d/www.conf
Currently, the environment variables for php-fpm in the docker image are all cleared. This makes it impossible to set a custom url prefix via TASMO_BASEURL, which is needed to run TasmoAdmins Docker image behind a reverse proxy. 
Leaving the env intact will probably fix the issue #140 and definitely #183
=> Remove clear_env from docker php config

tasmoadmin/pages/upload.php, tasmoadmin/pages/upload_form.php
The GitHub API requires passing a User-Agent so this was always failing.
By leveraging the version stored in the config we can provide them with something usable in their logs if they ever need to reach out to us.
=> Fix loading versions by passing user-agent

tasmoadmin/libs/phpi18n/i18n.class.php
array_shift() returns NULL if the array is empty. In PHP8, vsprintf() throws an error if the second parameter is not an array.
Casting NULL to an array creates an empty array.
This fixes #423.
Not sure yet if this is the only change to be made for PHP8 compatibility but at least I can log in and check further...
=> make sure vsprintf() is called with array

.docker/Dockerfile.alpine-tmpl, .docker/docker.sh, .github/workflows/main.yml, .gitignore, Makefile
- Wire up release flow (untested, any may fail)
- Add `Makefile` for packaging simplicity
- Make docker script exit 1 on wrong input (will cause CI to fail if so)
I think there could be lots of improvements still to be made. e.g. within the dockerfiles themselves and drop qemu to do multiarch builds simplier, but thats outside the scope of this.
=> Init of release

.docker/Dockerfile.alpine-tmpl, .docker/docker.sh, .dockerignore, .github/workflows/release.yml
- Use latest alpine image as base
- Bump QEMU version
- Include `.dockerignore` to improve build times
- Set default values in `docker.sh` to ease testing
To test
```bash
./.docker/docker.sh prepare
./.docker/docker.sh build
```
=> Improve docker build process

.docker/rootfs/etc/fix-attrs.d/01-tasmoadmin
I noticed when using the docker-compose stack the files were being owned by random UID making development really difficult.
This change makes s6 setup only ensure that the permissions are correctly set on the `tmp` dir which is where sessions and other "generated" files are created.
Not sure on the wider implication of this change? but it should be not an issue?
=> Fix docker permissions

.docker/Dockerfile.alpine-tmpl
When migrating to composer in #456 adding support for Parsedown requires the mbstring extension to be enabled.
=> Add mbstring dependency to docker setup

.docker/rootfs/etc/cont-init.d/16-persistent-data-tasmoadmin.sh, docker-compose.yml, tasmoadmin/includes/bootstrap.php
Right now the situation is that when the development environment starts up we have deleted files in the data directory.
With this change we allow the override of this data directory with the envvar `TASMOADMIN_DATADIR` while falling back to the current behaviour if this is not set.
=> Improve developer flow

.gitignore, tasmoadmin/composer.json, tasmoadmin/includes/bootstrap.php, tasmoadmin/src/Helper/JsonLanguageHelper.php, tasmoadmin/tests/Helper/JsonLanguageHelperTest.php, tasmoadmin/tests/bootstrap.php, tasmoadmin/tests/fixtures/language_en.ini
When migrating to composer I wasnt aware of the modifications to the language helper resulting in the JSON dumping being broken. This change introduces the language dumping support.
=> Fix JSON language dump

.docker/docker.sh
It's already pushed as `dev` since we set the `BUILD_VERSION` so we don't need to unify anything.
=> Fix dev docker push

tasmoadmin/includes/bootstrap.php
We've adopted PSR-4 autoloading with composer and this is redundant
=> Remove legacy autoload from bootstrap

.docker/rootfs/etc/cont-init.d/16-persistent-data-tasmoadmin.sh, .docker/rootfs/etc/nginx/nginx-ssl.conf, .docker/rootfs/etc/nginx/nginx.conf
Previously was unable to access mounted `.storage` firmware folder. With this change if `TASMO_DATADIR` not set remove the alias that fixes it.
=> Fix local dev for firmware path

.docker/rootfs/etc/cont-init.d/16-persistent-data-tasmoadmin.sh, .docker/rootfs/etc/nginx/nginx-ssl.conf, .docker/rootfs/etc/nginx/nginx.conf
Inject alias for local dev when `TASMO_DATADIR` env var set.
=> Use env var instead of hardcoding for local-dev

tasmoadmin/src/Helper/TasmotaHelper.php
Provide more graceful messaging for #658
=> Catch guzzle errors in tasotahelper

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Helper/IpHelper.php, tasmoadmin/tests/Helper/IpHelperTest.php
Limit the max amount of IPs to be scanned to 1024 whilst also fixing the IP range logic by leveraging PHP's built in functionality.
Resolves #667
=> Fix IP range logic

tasmoadmin/includes/header.php, tasmoadmin/pages/devices.php
=> Add basic device sorting

tasmoadmin/src/DeviceRepository.php, tasmoadmin/tests/DeviceRepositoryTest.php
Helps with #713
Previously it was setting the ID of new devices to the number of lines +1 which would cause issues when IDs were removed before hand.
With this change we take the largest Id and +1 to it to ensure more uniqueness.
=> Handle device IDs better

.github/workflows/main.yml
Since PHP 8.2 is now available we should support it.
=> Add PHP 8.2. to matrix test

tasmoadmin/pages/devices_details.php, tasmoadmin/pages/elements/devices_table.php
It's a relatively simple hack here, as it just check if username and password is set, then add it to the URL for automatic login on Tasmota's web UI. 
I'm a bit confused when I go through the code if the user didn't set the username (which should be "admin" by default) but rather the password only. On my end the behaviour is that the username will be simply empty if I edit a device, but will fallback to "admin" if I leave the field empty at the time of adding a new device in `devices.csv`. Also it seems when there's no username at all in `devices.csv` Tasmota will refuse the connection as username is not provided. I guess if this issue can be addressed, the code in this PR can be further improved (allows auto-login when username is not provided). 
Welcome suggestions 😃
=> Allow automatic HTTP Basic authentication on device list pages

Makefile, README.md
=> Streamline dev

.github/workflows/main.yml, tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/includes/preinstallchecks.php
Since PHP 7.4 is EOL since last year and with the other breaking changes in #756 it makes sense to bump the minimum supported version of PHP to 8.0.
=> Bump minimum PHP version to 8

tasmoadmin/src/Sonoff.php
I noticed the connect_timeout configuration wasn't set  - set this to something realistic.
=> Set connect_timeout on device client

tasmoadmin/includes/routes.php
Noticed `/devices_details` routing wasn't properly mapped - not sure who uses this page as it's not linked anywhere.
=> Fix routing for devices_details

tasmoadmin/resources/js/device_update.js
Now retries upto 2.5 minutes vs 1.5 minutes before.
=> Increase update retries to 15

tasmoadmin/pages/selfupdate.php, tasmoadmin/src/Helper/TasmoAdminHelper.php
As per #1017 this could be a better solution to dynamically load the changelog from GitHub API.
The implementation takes into account the update channel choosed in settings.
=> Dynamically loaded changelog from GitHub API

tasmoadmin/src/Config.php, tasmoadmin/tests/ConfigTest.php
Reverts TasmoAdmin/TasmoAdmin#1023
=> Revert "Config prep for API"

tasmoadmin/includes/header.php, tasmoadmin/lang/en/lang.ini, tasmoadmin/package-lock.json, tasmoadmin/package.json, tasmoadmin/pages/site_config.php, tasmoadmin/resources/js/device_update.js, tasmoadmin/src/Config.php
Add a new configuration option that allows upgrading to newer versions only.
Can be set to false in settings to allow downgrades.
=> By default only allow upgrades to newer versions

.tx/config
needs to be mapped to app otherwise won't work seamlessly.
=> Change transifex URL

tasmoadmin/includes/bootstrap.php, tasmoadmin/index.php
Resolves #1066
Previously session garbage collection was set to last for 1 year which seems insane - not sure why it was set to last so long :/
this change moves it back to the default of 24 minutes with the 1% change of it being cleaned up after that.
=> fix session lifetime

docker-compose.yml
No longer required - https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
=> Remove redundant version from docker-compose

tasmoadmin/includes/container.php, tasmoadmin/lang/en/lang.ini, tasmoadmin/pages/site_config.php, tasmoadmin/src/Config.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/SonoffTest.php
To stop TA sending as many requests as possible use a request pool to limit concurrency.
=> Control request concurrency

tasmoadmin/phpunit.xml.dist, tasmoadmin/src/DeviceRepository.php, tasmoadmin/tests/DeviceRepositoryTest.php
`escape` needs to be set in PHP 8.4 so explicitly handling it now
=> Fix fgetcsv and fputcsv deprecated warnings

.docker/Dockerfile.alpine-tmpl
Looks like 2.8.7 might have broke and 2.8.8 is not available yet.
=> Pin composer to 2.8.6

.docker/Dockerfile.alpine-tmpl
In preparation for adding Renovate extract dependency versions from Dockerfile configuration to make it easier to target through configuration.
=> Extract dependency versions in Docker configuration
