lang/lang_es.ini
=> Small typo correction

lang/lang_es.ini
=> Updated Spanish Translation

lang/lang_es.ini
=> Updated missing keys on spanish translation

lang/lang_nl.ini
Loaded in a running SonWEB to check if it is translated nicely :)
=> Revert devices.csv

tasmoadmin/lang/lang_ru.ini
correction of a typographical error
=> lang_ru fix

.iocage/README.md, .iocage/tasmoadmin-install.sh
@reloxx13 
Updated the README to use freebsd-version 11.2 for jail now. 11.1 is nearing end of life.
Also added, show very basic report with TasmoAdmin IP address at the end of install
=> update iocage install on FreeNAS

tasmoadmin/pages/site_config.php
=> Fix change username with empty pwd

tasmoadmin/helpers/login.php, tasmoadmin/login.php
- Use a more secure password hashing algorithm that'll evolve with time
- Provide upgrade path for passwords encrypted with `md5()`
p.s. I didn't test this - do you provide a Dockerfile to get going locally for development?
=> Leverage password_hash

.docker/docker.sh, .github/workflows/main.yml
=> [WIP] Migrate to GitHub Actions

tasmoadmin/pages/upload.php
- Remove ext from language output (should be changed probably)
- Add gzip status
=> Improve gzip output

tasmoadmin/lang/lang_de.ini
Added german translation for new gzip support.
=> Bigcookie german lang update for gzip support

.docker/Dockerfile.alpine-tmpl, .docker/docker.sh, .gitignore, Makefile, README.md, docker-compose.yml
- Add docker-compose setup
- Better make management with temp directories
- Add docker target to make
- Target x64 by default
There is slight conflict with git when starting due to the symlink of the data dir that on up marks the files in git as deleted. Not sure of a good way to handle that right now.
=> Add basic docker-compose setup + DX

.docker/Dockerfile.alpine-tmpl, .docker/docker.sh, .github/workflows/release.yml, Makefile, README.md
Potentially solve #473 by migrating to ghcr.io
@reloxx13 You could try pushing manually by following the steps here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
One limitation of this approach is that we are under your username vs an org could limit the collaboration as AFAIK only you can control the settings of the repo.
=> Migrate to ghcr.io

tasmoadmin/includes/Config.php, tasmoadmin/includes/Selfupdate.php
- Remove duplicate `.dockerenv` check
- Follow redirects with cURL for download updates (identified in #485
=> Tidy configuration layer

tasmoadmin/helpers/UrlHelper.php
- Remove unused functions
- Formatting
=> Tidy UrlHelper

.docker/docker.sh, .dockerignore, Makefile
- Exclude `.storage` from docker build
=> Tidy docker setup

tasmoadmin/composer.json, tasmoadmin/includes/bootstrap.php, tasmoadmin/src/Sonoff.php
- Adopt guzzle
- Fix doAjaxAll to use Guzzle promises
- Remove addDevice
- Improve doAjax
=> Fix Sonoff

tasmoadmin/pages/selfupdate.php, tasmoadmin/src/SelfUpdate.php
Was broken when adding composer support
=> Fix selfupdate.php

tasmoadmin/src/Sonoff.php
=> handle error state sonoff

.docker/docker.sh
=> Downgrade Alpine to from 3.15 -> 3.13

.github/workflows/main.yml, .github/workflows/release.yml
- Remove redundant permissions
- Rename for clarity
=> Tidy pipelines

tasmoadmin/composer.json, tasmoadmin/src/SelfUpdate.php
=> Fix selfupdate import

tasmoadmin/composer.json, tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Device.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/DeviceRepositoryTest.php, tasmoadmin/tests/DeviceTest.php, tasmoadmin/tests/Helper/JsonLanguageHelperTest.php, tasmoadmin/tests/TestUtils.php, tasmoadmin/tests/fixtures/devices.csv
Extract data layer from Sonoff into it's own class structure + add some tests
=> Rework device layer + add tests

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/src/Sonoff.php
Resolves #519 
- Wire up DeviceRepository params
- Fix field map
=> Fix up DeviceRepository setup

tasmoadmin/src/Config.php, tasmoadmin/tests/ConfigTest.php, tasmoadmin/tests/bootstrap.php
=> Config add basic test

tasmoadmin/pages/device_action.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/tests/DeviceRepositoryTest.php
=> Improve DeviceRepository

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Helper/IpHelper.php, tasmoadmin/tests/Helper/IpHelperTest.php
- Extract IP generation code
- Add tests
=> Extract IP generation

tasmoadmin/includes/bootstrap.php
When working on #456 something must have changed with translations that included placeholders. 
this change fixes those issues.
=> Fix placeholder translations

tasmoadmin/src/Sonoff.php
=> Improve Sonoff

tasmoadmin/pages/devices.php, tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Constants.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/SonoffTest.php
- Simplify seach using Guzzle
- Const usage for reuse
=> Sonoff simplification

tasmoadmin/pages/device_update.php, tasmoadmin/pages/upload.php, tasmoadmin/src/Config.php, tasmoadmin/src/Helper/FirmwareFolderHelper.php, tasmoadmin/src/Helper/OtaHelper.php, tasmoadmin/src/Helper/TasmotaHelper.php, tasmoadmin/src/Update/AutoFirmwareResult.php, tasmoadmin/src/Update/FirmwareDownloader.php, tasmoadmin/tests/Helper/FirmwareFolderHelperTest.php, tasmoadmin/tests/Helper/OtaHelperTest.php
- Rework upload into more modular code
- Add more tests
- make error notification come back
- Remove hide on click for alerts
=> Upload cleanup

tasmoadmin/composer.lock
=> Add composer.lock

tasmoadmin/includes/footer.php, tasmoadmin/includes/header.php, tasmoadmin/resources/js/app.js
Tidy variable reported in #554
=> Nighttime tidy

tasmoadmin/includes/bootstrap.php
=> Fix urlencode

tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/pages/selfupdate.php, tasmoadmin/src/Update/UpdateChecker.php, tasmoadmin/tests/Update/UpdateCheckerTest.php
Use SemVer comparison of version
Partial resolve of #552
=> Improve version comparison in update check

.docker/rootfs/etc/php7/php-fpm.d/www.conf, tasmoadmin/includes/bootstrap.php, tasmoadmin/pages/device_action.php
- Tidy `display_errors` usage
- Catch errors in php-fpm
=> Tidy error reporting

tasmoadmin/pages/device_action.php, tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Device.php, tasmoadmin/src/DeviceFactory.php
Should resolve https://github.com/hassio-addons/addon-tasmoadmin/issues/244#issuecomment-1159763003
=> Fix device actions

tasmoadmin/pages/device_action.php, tasmoadmin/pages/devices_autoscan.php
Not sure what the original intended name should have been but this seems more reasonable.
=> Fix missing translation for name adoption

tasmoadmin/includes/bootstrap.php
Reuse existing helper for cleaning firmware dir
=> Tidy bootstrap

tasmoadmin/src/Update/FirmwareChecker.php
=> Correct correct exception when checking firmware

tasmoadmin/pages/upload_form.php, tasmoadmin/src/Helper/TasmotaHelper.php
=> Build unified changelog

tasmoadmin/src/Helper/TasmotaHelper.php
Correctly solve #580 
Previously was merging both sources where in reality only a single one is needed as it contains the whole list.
=> Correct changelog resolution

tasmoadmin/src/Sonoff.php
- Remove deprecated function
- Tidy function types
- Remove redundant statements
=> Tidy Sonoff

tasmoadmin/src/Sonoff.php
Change timeout values of Guzzle to how they were before the refactor.
Related to #524 585
=> Fix guzzle timeout values

.docker/rootfs/etc/nginx/nginx.conf
=> Fix development nginx config

tasmoadmin/resources/js/device_update.js
- Fix OTA URL
- Add sleep
- Remove non-translated
=> Tidy device update js

tasmoadmin/resources/js/Sonoff.js, tasmoadmin/resources/js/devices.js, tasmoadmin/resources/js/start.js
- Turn to ES6 class
- Remove unused
=> Sonoff js tidy

tasmoadmin/resources/js/Sonoff.js
=> Fix JS refactor

tasmoadmin/includes/header.php, tasmoadmin/src/Helper/UrlHelper.php
=> Pass base URL into UrlHelper

tasmoadmin/includes/header.php, tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/site_config.php, tasmoadmin/pages/upload.php, tasmoadmin/resources/css/style.css, tasmoadmin/resources/js/device_update.js, tasmoadmin/src/Config.php
Add firmware checking config
- default on for backend check
- optional frontend checks
=> Add firmware checking config

tasmoadmin/pages/device_config.php, tasmoadmin/src/DeviceRepository.php
- Fix write changes from devices actions
- Tidy device config page
Resolves #624
=> Fix write changes on device actions + tidy device config

tasmoadmin/includes/header.php
=> Fix FE check

tasmoadmin/includes/header.php, tasmoadmin/resources/js/device_update.js
- Add check for `Unknown` command from backend
- Remove leading whitespace in translations
- Fix base_url
=> Translations + base URL

tasmoadmin/src/Sonoff.php
Resolves https://github.com/TasmoAdmin/TasmoAdmin/issues/609
=> Fix for PHP 8.1

tasmoadmin/pages/upload.php
Ensure that target version input set even on non-auto path.
=> Fix target version for non-auto path

tasmoadmin/resources/js/device_update.js
Fix version handling for dev builds
=> Fix version for dev

tasmoadmin/includes/header.php, tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/site_config.php, tasmoadmin/resources/js/device_update.js, tasmoadmin/src/Config.php
Prevent upgrading to the same version
=> Prevent same upgrade

.docker/Dockerfile.alpine-tmpl
- Skip dev dependencies for production
- optimise
=> Optmise composer for production

tasmoadmin/pages/start.php, tasmoadmin/resources/js/start.js
Potential resolve #632 
- format JS
- Change handler to use click instead of mouseup and touchend
=> Fix start click

.github/workflows/release.yml, .gitignore, tasmoadmin/src/Config.php
Resolves #552
- Generate `.version` file on release
=> Generate .version on release

tasmoadmin/src/Config.php
=> Fix version write

tasmoadmin/includes/header.php, tasmoadmin/src/Helper/UrlHelper.php
- Fix for minification by passing back resourceDir
- Consolidate config read
=> Fix URLHelper for min

tasmoadmin/resources/js/device_update.js
Boolean condition was wrong - it should have been `!config.force_upgrade`
=> Fix force upgrade flag

tasmoadmin/includes/header.php, tasmoadmin/resources/css/all.css
You can get the same results with browser debuggers
=> Remove legacy CSS/HTML debug

.github/workflows/main.yml, .gitignore, codecov.yml, tasmoadmin/phpunit.xml.dist
Add codecov support to the pipeline
=> Add codecov

tasmoadmin/src/Helper/IpHelper.php, tasmoadmin/tests/Helper/IpHelperTest.php
=> Improve memory efficency of IP generation

tasmoadmin/composer.json
Add missing `ext-dom` dependency to composer.json
=> Add ext-dom dependency

tasmoadmin/includes/bootstrap.php, tasmoadmin/resources/js/app.js, tasmoadmin/src/Helper/JsonLanguageHelper.php, tasmoadmin/tests/Helper/JsonLanguageHelperTest.php, tasmoadmin/tests/fixtures/language_de.ini
Provides English fallback for missing translations 
Resolves missing translations in #683
=> Add fallback to JavaScript languages

tasmoadmin/src/Helper/JsonLanguageHelper.php
Take into consideration fallback file on cache bust
Related to #683
=> Fix Cache bust on JS file

tasmoadmin/pages/upload.php
=> Prevent not including minimal breaking update

tasmoadmin/pages/upload_form.php, tasmoadmin/src/Config.php
- Read once on upload_form
- Improve readability of Config
=> Optimise config

tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/includes/bootstrap.php, tasmoadmin/includes/container.php, tasmoadmin/includes/header.php, tasmoadmin/pages/devices.php, tasmoadmin/src/Config.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/ConfigTest.php, tasmoadmin/tests/Helper/OtaHelperTest.php, tasmoadmin/tests/SonoffTest.php, tasmoadmin/tests/bootstrap.php
Add container for resolving classes from
=> Add container foundations

tasmoadmin/pages/devices.php
Was missing `data-tablesaw-sortable-numeric` attribute
=> Fix RSSI sort

tasmoadmin/includes/preinstallchecks.php, tasmoadmin/pages/selfupdate.php, tasmoadmin/src/SelfUpdate.php, tasmoadmin/src/Update/UpdateChecker.php
- Simply selfupgrade code with Guzzle
- Setup basic pre-install checks
=> Setup basic pre-install checks for non-container installs

tasmoadmin/pages/selfupdate.php, tasmoadmin/src/SelfUpdate.php, tasmoadmin/src/Update/UpdateChecker.php
Improve output on update failure
=> Make update check red on failure

tasmoadmin/src/Sonoff.php, tasmoadmin/tests/SonoffTest.php
- Improve function readability
- Remove redundant parameter
- Add tests
=> Tidy Sonoff->getDevices

tasmoadmin/src/Sonoff.php, tasmoadmin/src/Tasmota/ResponseParser.php, tasmoadmin/tests/Tasmota/ResponseParserTest.php
Allow extending response parser for easier testing
=> Extract response parser

tasmoadmin/pages/upload.php
=> Make upload sortable

tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/backup.php, tasmoadmin/pages/upload.php
- Tidy up where locales are stored
- Added backup header
=> Tidy backup locales

tasmoadmin/src/Helper/BackupHelper.php
If device is not online or there is a HTTP issue, gracefully skip.
Could be improved with messaging of what was skipped etc in the future
=> gracefully skip devices that have connection issues

tasmoadmin/includes/container.php, tasmoadmin/pages/backup.php, tasmoadmin/src/Backup/BackupHelper.php, tasmoadmin/src/Backup/BackupResult.php, tasmoadmin/src/Backup/BackupResults.php
- Add `BackupResults` to allow for messaging about skipped devices
- Remove accidental zip opening on backup
=> Introduce backup result object

tasmoadmin/includes/bootstrap.php, tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/backup.php, tasmoadmin/src/Backup/BackupHelper.php, tasmoadmin/src/Backup/BackupResult.php, tasmoadmin/src/Backup/BackupResults.php, tasmoadmin/src/Device.php, tasmoadmin/src/Sonoff.php
=> Improve backup messaging

tasmoadmin/lang/lang_en.ini, tasmoadmin/pages/backup.php
=> Improve backup message

tasmoadmin/includes/container.php, tasmoadmin/includes/header.php, tasmoadmin/pages/devices_details.php, tasmoadmin/src/Helper/ViewHelper.php
Move nightmode logic to view helper
=> ViewHelper for tidying up nightmode

tasmoadmin/pages/devices.php, tasmoadmin/pages/elements/devices_table.php
Refactoring the table element i overlooked the commands column being used.
Resolves #759
=> Fix bug with command dispatching

tasmoadmin/pages/devices_details.php, tasmoadmin/pages/elements/devices_table.php, tasmoadmin/src/Device.php, tasmoadmin/tests/DeviceTest.php
=> Refactor HTTP basic auto login

tasmoadmin/pages/elements/devices_table.php
=> Add back position to device table

tasmoadmin/resources/js/devices.js
=> Fix device toggle on update

.docker/rootfs/etc/nginx/nginx-ssl.conf, .docker/rootfs/etc/nginx/nginx.conf, tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/includes/bootstrap.php, tasmoadmin/includes/routes.php, tasmoadmin/index.php, tasmoadmin/pages/change_language.php, tasmoadmin/pages/chat.php, tasmoadmin/pages/device_action.php, tasmoadmin/pages/device_config.php, tasmoadmin/pages/login.php, tasmoadmin/pages/logout.php, tasmoadmin/resources/js/Sonoff.js, tasmoadmin/resources/js/app.js
Improve routing by moving it into code land to avoid having to depend on web-server config to allow an easier evolution of the platform.
=> Move routing into application logic

.github/workflows/main.yml, UPGRADE.md, tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/includes/preinstallchecks.php, tasmoadmin/tests/Helper/IpHelperTest.php, tasmoadmin/tests/Tasmota/ResponseParserTest.php
Previously bumped PHP min to 8.0 but makes sense to go to 8.1 considering that 8 is only in maintenance mode since two weeks.
- Bumped related dependencies as well
=> Bump PHP to 8.1

tasmoadmin/src/Helper/TasmotaHelper.php
=> Fix PHP 8.2 deprecated warning

tasmoadmin/.htaccess
Add missing `.htaccess` for the changes made in routing
Related to #787
=> Add htaccess

tasmoadmin/resources/js/app.js, tasmoadmin/resources/js/start.js
- Add total power
- Tidy output + JS
Resolves #796
=> Add total power on start and tabular view

tasmoadmin/resources/js/device_update.js
Remove non-needed front controller
=> Fix device update JS

.docker/Dockerfile.apache, .docker/apache_startup.sh, Makefile, docker-compose.yml, tasmoadmin/includes/bootstrap.php
Add Apache support for easier debugging of that webserver + config
=> Add apache setup for easier debugging

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Config.php
- Stop writing config when version hasn't changed
- Remove unused variable
=> Stop thrashing writing version

tasmoadmin/src/Backup/BackupHelper.php, tasmoadmin/src/Device.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/DeviceTest.php
- Convert `/` to `_` in backup path + add tests
Resolves #776
=> Fix slash in backup file path

tasmoadmin/pages/backup.php
Missed during moving routes inline
=> Strip index.php from backup routing

tasmoadmin/resources/js/Sonoff.js, tasmoadmin/resources/js/app.js, tasmoadmin/resources/js/devices.js, tasmoadmin/resources/js/devices_details.js, tasmoadmin/resources/js/start.js
Tidy JS for wifi information to allow easier conditionally removing things for devices that don't have wifi
- Remove commented elements
- Remove broken JavaScript
=> Tidy wifi status JS

.github/workflows/release.yml
Resolves https://github.com/hassio-addons/addon-tasmoadmin/issues/285
=> Correct release PHP version

tasmoadmin/index.php
=> Fix load homepage from config

.docker/rootfs/etc/nginx/nginx-ssl.conf, .docker/rootfs/etc/nginx/nginx.conf
Doesn't really add much protection and we already have a robots.txt which prevents good bots from crawling.
Resolves #821
=> Cleanup nginx for bots

tasmoadmin/data/firmwares/.htaccess
Add CORS header for FE check for Apache.
Related #810
=> Add apache cors for firmware dir

tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/pages/site_config.php, tasmoadmin/pages/upload.php, tasmoadmin/pages/upload_form.php, tasmoadmin/src/Helper/TasmotaOtaScraper.php, tasmoadmin/tests/Helper/TasmotaOtaScraperTest.php
Project was deprecated https://github.com/FriendsOfPHP/Goutte/tree/v4.0.3
=> Migrate from deprecated Goutte

tasmoadmin/includes/bootstrap.php, tasmoadmin/includes/preinstallchecks.php
=> Make error messages more generic

tasmoadmin/pages/site_config.php, tasmoadmin/pages/upload.php, tasmoadmin/pages/upload_form.php, tasmoadmin/src/Config.php, tasmoadmin/src/Helper/OtaHelper.php
=> Remove HTTPS from OTA update as unsupported

tasmoadmin/pages/site_config.php, tasmoadmin/src/Helper/LoginHelper.php
- Tidy settings post logic
- Fix saving md5 on passord update and use password_hash consistently
=> Tidy settings persist

tasmoadmin/pages/site_config.php, tasmoadmin/phpunit.xml.dist, tasmoadmin/src/Config.php, tasmoadmin/tests/ConfigTest.php
- Add cleanConfig function to remove unused keys
- Add writeAll to prevent writing lots 
- Migrate out of date config for phpunit
=> Clean configuration + writeAll

tasmoadmin/pages/upload.php
Messages were not properly collecting
Related to #810
=> Fix message display on upload

.docker/rootfs/etc/s6-overlay/s6-rc.d/init-tasmoadmin/up, .docker/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
Fix missing bits with s6 migration
=> Fix S6 migration

tasmoadmin/lang/en/lang.ini, tasmoadmin/resources/css/all.css, tasmoadmin/resources/js/device_update.js
Add overview of update results to indicate success of update process
=> Add global result logline

tasmoadmin/pages/device_update.php, tasmoadmin/resources/js/device_update.js, tasmoadmin/src/DeviceRepository.php
Modify update process to load device information before going through update loop.
=> Add device name in update

tasmoadmin/lang/en/lang.ini, tasmoadmin/pages/device_action.php, tasmoadmin/pages/device_update.php, tasmoadmin/pages/elements/devices_table.php, tasmoadmin/pages/upload.php, tasmoadmin/resources/js/devices.js, tasmoadmin/src/Device.php, tasmoadmin/src/DeviceFactory.php, tasmoadmin/src/DeviceRepository.php
Add new device setting "is updatable" which by default is true
Resolves #940
=> Device setting to flag device as updatable or not 

tasmoadmin/phpstan.neon.dist, tasmoadmin/src/Tasmota/ResponseParser.php, tasmoadmin/tests/Helper/JsonLanguageHelperTest.php
- Bump PHPStan level to 2
- Fix issues + bug
=> Bump phpstan to 2

tasmoadmin/phpstan.neon.dist, tasmoadmin/src/Device.php, tasmoadmin/src/DeviceFactory.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/DeviceFactoryTest.php, tasmoadmin/tests/SonoffTest.php
- Change position to be `int` in Device - default to `0` for unknown
=> Bump phpstan to 4

tasmoadmin/includes/bootstrap.php
Noticed these actions were previously able to be called without authentication.
=> Prevent calling actions without being logged in

tasmoadmin/includes/bootstrap.php, tasmoadmin/phpstan.neon.dist, tasmoadmin/src/DeviceFactory.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/src/SelfUpdate.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/DeviceRepositoryTest.php, tasmoadmin/tests/DeviceTest.php
- Change Device ID from string to int
- Fix other type issues
=> Bump PHPStan to 5

tasmoadmin/.php-cs-fixer.dist.php, tasmoadmin/includes/bootstrap.php, tasmoadmin/includes/routes.php, tasmoadmin/index.php, tasmoadmin/pages/actions.php, tasmoadmin/pages/backup.php, tasmoadmin/pages/change_language.php, tasmoadmin/pages/device_action.php, tasmoadmin/pages/device_config.php, tasmoadmin/pages/device_config_tabs/config_general_tab.php, tasmoadmin/pages/device_config_tabs/config_mqtt_tab.php, tasmoadmin/pages/device_config_tabs/config_network_tab.php, tasmoadmin/pages/devices.php, tasmoadmin/pages/devices_autoscan.php, tasmoadmin/pages/devices_details.php, tasmoadmin/pages/elements/devices_table.php, tasmoadmin/pages/elements/modal_delete_device.php, tasmoadmin/pages/login.php, tasmoadmin/pages/selfupdate.php, tasmoadmin/pages/site_config.php, tasmoadmin/pages/start.php, tasmoadmin/pages/upload.php, tasmoadmin/pages/upload_form.php, tasmoadmin/resources/js/Sonoff.js, tasmoadmin/resources/js/device_update.js
- Add `render_template` and `render_raw` to allow various rendering on a route level
- move bootstrap logic to route protected pages
=> Fix routing

tasmoadmin/resources/js/Sonoff.js, tasmoadmin/resources/js/app.js, tasmoadmin/resources/js/device_update.js
=> Fix ajax calls by passing base_url when TASMO_BASEURL specified

CHANGELOG.md
=> Rework changelog text for migration to releases

tasmoadmin/src/Config.php, tasmoadmin/tests/ConfigTest.php
- Remove session logic from config
- Tidy duplicate code
=> Config prep for API

tasmoadmin/src/Config.php, tasmoadmin/tests/ConfigTest.php
- Remove `$_SESSION` from configuration
- Consolidate writing config
=> Tidy up configuration

tasmoadmin/src/Config.php
=> Reduce duplication in config functions

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/pages/site_config.php, tasmoadmin/src/Config.php
- Use in memory cache for config read access
- invalid on write
=> Cache config reading

tasmoadmin/includes/bootstrap.php, tasmoadmin/src/DeviceRepository.php, tasmoadmin/tests/DeviceRepositoryTest.php, tasmoadmin/tests/SonoffTest.php
- Move IO check into repository 
- make tests nicer
=> Tidy bootstrap code

tasmoadmin/pages/device_action.php, tasmoadmin/resources/js/app.js, tasmoadmin/resources/js/device_config.js, tasmoadmin/resources/js/devices.js, tasmoadmin/resources/js/start.js
- Remove some commented out code
- Remove useless console logs
=> Tidy up JS

Makefile
Shrink the resulting packages down in size
=> Remove node_modules after package

tasmoadmin/tests/Tasmota/ResponseParserTest.php, tasmoadmin/tests/fixtures/response-invalid-v5100.json
Use fixture to test old tese case
=> Add v5100 test case

tasmoadmin/src/Device.php, tasmoadmin/src/DeviceFactory.php, tasmoadmin/tests/DeviceFactoryTest.php
- Tidy constructor for Device
- Add additonal name tests
=> Tidy Device class + more tests

tasmoadmin/package-lock.json, tasmoadmin/package.json
Reverts TasmoAdmin/TasmoAdmin#1112
=> Revert "Bump bootstrap from 4.6.2 to 5.3.3 in /tasmoadmin"

.github/workflows/main.yml
=> Add PHP 8.3 to CI for tests

tasmoadmin/pages/device_action.php, tasmoadmin/src/Device.php, tasmoadmin/src/DeviceFactory.php, tasmoadmin/tests/DeviceTest.php, tasmoadmin/tests/SonoffTest.php
- Add missing port addition change to Device URL helper
- Change device props from int to bool
=> Port addition left over + device prop to bool

.github/workflows/release.yml
- Split release pipeline in two
=> Improve release pipeline

tasmoadmin/resources/js/devices.js
Potential resolution for #1185
=> Fix edit tabular view

tasmoadmin/pages/upload.php
Resolves #1235 
- Increase upload to 5mb
- Fix error format
=> Increase upload to 5MB

tasmoadmin/includes/container.php, tasmoadmin/lang/en/lang.ini, tasmoadmin/pages/site_config.php, tasmoadmin/src/Config.php, tasmoadmin/src/Http/HttpClientFactory.php, tasmoadmin/src/Sonoff.php, tasmoadmin/tests/SonoffTest.php
To allow timeout settings to be configurable
=> Move client to be configurable

tasmoadmin/lang/en/lang.ini
=> Fix copy for config

tasmoadmin/includes/header.php, tasmoadmin/resources/js/app.js, tasmoadmin/resources/js/devices.js, tasmoadmin/resources/js/start.js
Missed the ajax request concurrency from #1255
Should help with https://github.com/hassio-addons/addon-tasmoadmin/issues/435
=> Limit ajax concurrency

.docker/Dockerfile.alpine-tmpl, .docker/docker.sh
Due to https://github.com/docker-library/official-images/issues/17896 we now need to pass platform when building
Unfortunately there is an issue with node on arm/v6 :/ so had to use arm/v7 using slim
=> Fix docker builds

tasmoadmin/composer.json, tasmoadmin/composer.lock, tasmoadmin/phpstan.neon.dist
- Add deprecated plugin
- Tidy up
=> Tighten PHPStan

Makefile, tasmoadmin/.php-cs-fixer.dist.php, tasmoadmin/index.php, tasmoadmin/info.php, tasmoadmin/pages/actions.php, tasmoadmin/pages/backup.php, tasmoadmin/pages/device_action.php, tasmoadmin/pages/device_config.php, tasmoadmin/pages/device_config_tabs/config_general_tab.php, tasmoadmin/pages/device_config_tabs/config_mqtt_tab.php, tasmoadmin/pages/device_config_tabs/config_network_tab.php, tasmoadmin/pages/device_update.php, tasmoadmin/pages/devices.php, tasmoadmin/pages/devices_autoscan.php, tasmoadmin/pages/elements/devices_table.php, tasmoadmin/pages/elements/modal_delete_device.php, tasmoadmin/pages/login.php, tasmoadmin/pages/logout.php, tasmoadmin/pages/selfupdate.php, tasmoadmin/pages/site_config.php, tasmoadmin/pages/start.php, tasmoadmin/pages/upload.php, tasmoadmin/pages/upload_form.php
- Add pages to `php-cs-fixer` check
- Improve quality make goal to clean cache files first
=> Add pages to php-cs-fixer lint

tasmoadmin/pages/actions.php, tasmoadmin/pages/device_action.php, tasmoadmin/resources/js/devices.js, tasmoadmin/src/DeviceRepository.php, tasmoadmin/tests/DeviceRepositoryTest.php
Previously it would update the file per selected device, now it does it as a single operation
=> Improve device removal logic

.docker/Dockerfile.alpine-tmpl
=> Fix params in docker build

docker-compose.yml
=> Use diff volume for tmp files in local dev

tasmoadmin/pages/devices_autoscan.php, tasmoadmin/src/Device.php, tasmoadmin/tests/DeviceTest.php
- autoscan skipping factors in port so you can add multiple devices on the same IP
- more tests
=> autoscan skipping factors in port
